### ISSUE TITLE
Segmentation fault when indenting/unindenting from menu

### ISSUE THREAD

**Issue by magiblot** [gphalkes/tilde#43]
![Screenshot_20190421_212233](https://user-images.githubusercontent.com/20713561/56474540-9f6d3480-647b-11e9-8032-24eba26c19ea.png)

Tilde crashes when the menu options are used but no text is selected (the Tab / Shift+Tab key combinations work as expected).

Backtrace:
```
Thread 1 "tilde" received signal SIGSEGV, Segmentation fault.
0x00007f5ac37aef40 in t3widget::text_line_t::size() const () from /usr/lib/libt3widget.so.2
(gdb) bt
#0  0x00007f5ac37aef40 in t3widget::text_line_t::size() const () from /usr/lib/libt3widget.so.2
#1  0x00007f5ac379f672 in t3widget::edit_window_t::ensure_cursor_on_screen() () from /usr/lib/libt3widget.so.2
#2  0x00007f5ac37a0c87 in t3widget::edit_window_t::indent_selection() () from /usr/lib/libt3widget.so.2
#3  0x00005634a01c2cea in ?? ()
#4  0x00005634a01c90a9 in ?? ()
#5  0x00005634a01cc90a in ?? ()
#6  0x00007f5ac37b7e39 in std::_Function_handler<void (int), t3widget::signal_t<int>::get_trigger() const::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) () from /usr/lib/libt3widget.so.2
#7  0x00007f5ac3778d19 in t3widget::menu_panel_t::activate(int) () from /usr/lib/libt3widget.so.2
#8  0x00007f5ac376d0cb in t3widget::menu_item_t::process_mouse_event_from_menu(t3widget::mouse_event_t) () from /usr/lib/libt3widget.so.2
#9  0x00007f5ac3777df0 in t3widget::menu_panel_t::process_mouse_event(t3widget::mouse_event_t) () from /usr/lib/libt3widget.so.2
#10 0x00007f5ac37b7015 in t3widget::menu_bar_t::process_mouse_event(t3widget::mouse_event_t) () from /usr/lib/libt3widget.so.2
#11 0x00007f5ac378cacb in t3widget::mouse_target_t::handle_mouse_event(t3widget::mouse_event_t) () from /usr/lib/libt3widget.so.2
#12 0x00007f5ac375ddc1 in t3widget::iterate() () from /usr/lib/libt3widget.so.2
#13 0x00007f5ac375deae in t3widget::main_loop() () from /usr/lib/libt3widget.so.2
#14 0x00005634a01c5162 in ?? ()
#15 0x00007f5ac336a223 in __libc_start_main () from /usr/lib/libc.so.6
#16 0x00005634a019d96e in ?? ()
```
These two menu entries probably should just do the same as the key bindings, instead of being limited to selected text (Shift+Tab, for instance, can't be recognized in the linux console, so the menu entry could be used instead).

Cheers.

**Comment by gphalkes** [comment]
That is pretty bad. I'm able to reproduce, and I'll get onto fixing this asap. Thanks for reporting!

**Comment by gphalkes** [comment]
This is fixed by libt3widget commit https://github.com/gphalkes/t3widget/commit/1586ee368645e5ac206d45dacb83b27516e28f53. Release 1.0.6 of libt3widget contains the fix.

**Comment by magiblot** [comment]
Thanks!
